### ISSUE TITLE
Kitap eklerken kitabın ismi, yazarı ve yayınevi zorunlu olmalı

### ISSUE THREAD

**Issue by ykptke** [ilterisayvaci/books-list-react#1]
Kitap eklerken hiçbir şey yazmadığım halde kitabı ekliyor. Eklememesi lazım.
![screenshot from 2017-06-02 10-58-24](https://cloud.githubusercontent.com/assets/3853299/26716520/6d0cfe66-4782-11e7-8b0a-3a9b95461d92.png)

**Comment by ilterisayvaci** [comment]
Gerektiği şekilde kodlar güncellenmiştir.
